server.port=8443

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.phone=${ADMIN_PHONE}

frontend.base.url=${FRONTEND_BASE_URL}
images.base.url=${IMAGES_BASE_URL}

# SSL
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mercato

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Email Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_SMTP_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.default-encoding=UTF-8

# Email sender configuration
mercato.email.from=${EMAIL_FROM}

# Email verification settings
mercato.email.verification.expiry-hours=24

# JWT
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_TTL}

#cashfree
cashfree.app.id=${CASHFREE_APP_ID}
cashfree.secret.key=${CASHFREE_SECRET_KEY}
cashfree.base.url=${CASHFREE_BASE_URL}
cashfree.api.version=${CASHFREE_API_VERSION}
cashfree.return.url=${CASHFREE_RETURN_URL}
cashfree.notify.url=${CASHFREE_NOTIFY_URL}

images.products.folder=assets/images/products
images.products.placeholder.url=${IMAGES_PLACEHOLDER_URL}

# User Account Cleanup Configuration
mercato.account.cleanup.enabled=true
mercato.account.cleanup.retention-days=7
mercato.account.cleanup.cron=0 0 2 * * *

logging.level.org.springframework.security=ERROR
logging.level.org.hibernate=ERROR