spring.application.name=mercato-backend

cart.item.reservation.minutes=45
cart.reservation.cleanup.interval.ms=900000

cart.shipping.threshold=999
cart.shipping.charge=50
cart.platform.fee=12

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB

spring.mvc.async.request-timeout=30000
spring.mvc.pathmatch.use-suffix-pattern=false